server:
  port: 8887
#  解决浏览器第一次访问首页，登录后url变成 http://localhost:8887/;jsessionid=66FB6BC4B5DCB72A176EDDC53D759AB3
#  导致 无法显示问题列表 的问题
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true

github:
  client:
    id: 9706d72cdbecf1898ce0
    secret: 5cbabe5f152ee88ff9d7a99df2d19471bc5de400
  redirect:
    uri: http://localhost:8887/callback


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:13306/community?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456


#去除spring图标
  main:
    banner-mode: off

#Mp相关的配置
mybatis-plus:
  #开启日志，能看到SQL语句
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  去除mybatis-plus图标
  global-config:
    banner: false

#  指定XML方式自定义SQL的XML文件位置
  mapper-locations: classpath:mapper/*.xml
#  指定返回值类型(实体类)的位置，这样在XML文件中的返回值需要返回实体类时，可以直接写实体类，不用带上包名
  type-aliases-package: life.majiang.community.domain


#日志
logging:
  file:
    name: logs/community.log
  level:
#    根目录的info级别日志
    root: info
#    MyBatis-Plus的debug级别日志
#    life:
#      majiang:
#        community:
#          dao: debug
  logback:
    rollingpolicy:
#      日志文件最大存储容量
      max-file-size: 100MB
#      最大历史文件数(以天为单位)
      max-history: 30